### ISSUE TITLE
Node.js와 Database 연동

### ISSUE THREAD

**Issue by onnoo** [onnoo/hycora-web-project#10]
### Node.js 서버로부터 Database 서버와 통신하기 위한 코드 작성

- [ ] `localhost:3000/users` 로 접속 시 `routes/users.js` 파일이 해당 요청을 처리합니다.

- [ ] DB의 contributors 테이블의 데이터를 가져와 json 형식으로 클라이언트에게 응답합니다. (`res.json` [참고](https://expressjs.com/ko/api.html#res.json))

아마 MySQL과 통신을 도와주는 npm 모듈이 있을겁니다.

**Comment by cwyoon-99** [comment]
제가 하겠습니다
