### ISSUE TITLE
comments 테이블 date 컬럼 수정

### ISSUE THREAD

**Issue by onnoo** [onnoo/hycora-web-project#11]
### date 현재 시간 자동 삽입

```
DESC comment
```

| Field   | Type         | Null | Key | Default | Extra |
|---------|--------------|------|-----|---------|-------|
| id      | varchar(255) | NO   | PRI | NULL    |       |
| content | varchar(255) | NO   |     | NULL    |       |
| date    | datetime     | YES  |     | NULL    |       |

현재 comment 테이블의 date 컬럼은 Null 값이 허용됩니다.

새로운 행을 insert 할 경우, 현재 시간을 기본 값으로 추가되도록 MySQL을 통해 컬럼 설정을 변경합니다.

**Comment by sochubert** [comment]
제가 수정하겠습니다~

**Comment by onnoo** [comment]
> date 한국 시간으로 잘 들어가는 것은 확인했습니다!

목표했던 게시판은 익명 게시판이었습니다.

기존에 USER_ID 부분이 사용자 이름이 아니라 primary key를 위한 id 컬럼이였습니다. 이 부분은 AUTO_INCREMENT 필요하구요. 이 부분 수정 부탁드립니다!
