### ISSUE TITLE
DB 데이터 HTML table로 나타내기

### ISSUE THREAD

**Issue by onnoo** [onnoo/hycora-web-project#16]
### Background

`routes/users.js` 파일을 보면, mysql 서버와 통신하는 코드가 작성되어 있습니다. (4번 ~ 12번 line)

20번 라인에서 EJS 렌더링 시 쿼리 결과를 함께 전달합니다.

### Todo

- [ ] EJS 문법 살펴보기 `<%= %>` 와 `<%- %>` 의 차이

- [ ] `views/users.ejs` 를 확인하고 EJS 문법을 고려하여 쿼리 결과를 HTML table 형태로 나타내기 (`table` tag)

**Comment by sochubert** [comment]
지원~
