### ISSUE TITLE
Index 페이지 ul 태그 CSS 작성

### ISSUE THREAD

**Issue by onnoo** [onnoo/hycora-web-project#19]
### Background

* [링크](http://www.walterz.net/2017/07/31/css-%EA%B9%94%EB%81%94%ED%95%9C-%EB%AA%A9%EB%A1%9D-%EC%8A%A4%ED%83%80%EC%9D%BC-css-list-style/) 를 참고하셔서 `views/index.ejs` 의 div 태그 내부에 ul 리스트를 작성해 주세요.

* css 파일의 경로는 `public/stylesheets/style.css` 입니다.

### Todo
![image](https://user-images.githubusercontent.com/29935117/95642399-3fd96d80-0ae3-11eb-86c7-2b75c2352521.png)

**Comment by sorongosdev** [comment]
제가 해도 될까요!

**Comment by onnoo** [comment]
넵 먼저 코멘트 다시고 진행하시면 됩니다! 하다가 잘 안되면 편하게 물어보세요

**Comment by sorongosdev** [comment]
네ㅎㅎㅎ
