### ISSUE TITLE
렌더링 엔진 EJS로 변경하기

### ISSUE THREAD

**Issue by onnoo** [onnoo/hycora-web-project#2]
현재 렌더링 엔진이 `pug`로 되어 있는데, 아직 html이 익숙하지 않은 경우 진입 장벽이 있다고 생각됩니다.

그래서 html과 유사한 `ejs` 엔진으로 변경하는 작업이 필요할 것 같습니다.

기존에 views 폴더에 있던 `error.pug`, `index.pug`, `layout.pug` 도 각각 .ejs 포맷(html과 동일)에 맞춰서 재작성해주세요!

**Comment by sochubert** [comment]
test
