### ISSUE TITLE
Index 페이지 Nav bar 생성

### ISSUE THREAD

**Issue by onnoo** [onnoo/hycora-web-project#24]
### Background

현재 홈페이지에는 두가지 페이지가 존재합니다.
* `/`
* `/users`

각 페이지의 상단에 페이지 이동을 위한 Navigation Bar가 있으면 좋겠습니다. 형식은 구글링을 통해 마음에 드는 스타일 가져오셔도 됩니다. (필요하다면 `public/stylesheets/style.css` 수정 가능)

### Todo

- [ ] 모든 페이지 상단에 Navigation Bar 작성하기

- [ ] 가능하다면 동아리 이름도 넣어둘 것!

**Comment by sorongosdev** [comment]
제가 할게요!
