### ISSUE TITLE
Users 페이지 디자인 입히기

### ISSUE THREAD

**Issue by onnoo** [onnoo/hycora-web-project#29]
### Background

* 현재 Index 페이지는 어느정도 디자인이 완료되었지만, Users 페이지는 디자인이 완성되지 않았습니다.

* 브라우저의 개발자 도구를 통해 여러 페이지들의 CSS 값을 확인해 볼 수 있습니다! 이를 통해 영감을 수집하세요 👍 

* 여러 사람들이 함께 참여하셔도 좋습니다.

### Todo

- [x] CSS, JS를 활용하여 `views/users.ejs` 페이지에 스타일을 적용시킵니다. (정해진 형식은 없습니다.)

**Comment by sochubert** [comment]
우선 1차적으로 제가 참여해서 수정 해 보겠습니다~

**Comment by onnoo** [comment]
꼭 테이블 형태가 아니어도 좋습니다 :)
