### ISSUE TITLE
(DB 실습) Contributor 테이블에 자신의 정보 추가하기

### ISSUE THREAD

**Issue by onnoo** [onnoo/hycora-web-project#30]
### Background

* users 페이지는 데이터베이스의 `contributors` 테이블을 정보를 가져옵니다.

* 아직 테이블에 데이터가 추가되어 있지 않은 분들은 직접 자신의 정보를 SQL 작성을 통해 INSERT 해 보세요.

* DB 조작을 위해서 어떤 툴을 사용할 지는 자유입니다!

### Todo

- [x] @dosora1 

- [x] @qicqock 

- [x] @1004gite

- [x] @sochubert

**Comment by onnoo** [comment]
DB 접속 정보은 저 또는 @sochubert 에게 물어보세요.

**Comment by sochubert** [comment]
DB가 설치되어 있다고 가정하고 절차를 알려드리자면, (맥 기준)
터미널을 켜시고
1. mysql -h un0jueuv2mam78uv.cbetxkdyhwsb.us-east-1.rds.amazonaws.com -u g9nik0gsfr2xcvl0 -p //접속 절차-1
2. fw5levjz4ldksb6c //접속 절차-2(password)
3. USE zp4vot7umqtxfib1 //데이터 베이스 사용

그 후, SHOW TABLES 등을 통해서 스키마 이름을 확인 하신 후, 자유롭게 작업 해 보시면 됩니다~

**Comment by onnoo** [comment]
> DB가 설치되어 있다고 가정하고 절차를 알려드리자면, (맥 기준)
> 터미널을 켜시고
> 
> 1. mysql -h un0jueuv2mam78uv.cbetxkdyhwsb.us-east-1.rds.amazonaws.com -u g9nik0gsfr2xcvl0 -p //접속 절차-1
> 2. fw5levjz4ldksb6c //접속 절차-2(password)
> 3. USE zp4vot7umqtxfib1 //데이터 베이스 사용
> 
> 그 후, SHOW TABLES 등을 통해서 스키마 이름을 확인 하신 후, 자유롭게 작업 해 보시면 됩니다~

MAC 에서 mysql CLI를 사용할 때 참고가 될 것 같습니다.

**Comment by 1004gite** [comment]
추가했습니다!

**Comment by sochubert** [comment]
최종적으로 추가 모두 마쳤습니다.
