### ISSUE TITLE
한마디 테이블 설계

### ISSUE THREAD

**Issue by onnoo** [onnoo/hycora-web-project#7]
Columns : id(PK), content, date

Assignee 에게 DB 접속 정보를 전달하겠습니다.

**Comment by sochubert** [comment]
능력은 부족한데, 보조로 참여는 해 보고 싶습니다~

**Comment by onnoo** [comment]
한마디 게시판 레퍼런스입니다!
![1](https://user-images.githubusercontent.com/29935117/95535353-31c41800-0a23-11eb-9024-7284ca6906cd.PNG)
