### ISSUE TITLE
Index 페이지 레이아웃 구성

### ISSUE THREAD

**Issue by onnoo** [onnoo/hycora-web-project#8]
현재 Index 페이지 (`views/index.ejs`) 부분이 Express 기본 내용으로 구성되어 있습니다. 타이틀도 포함해서요.

형식은 상관없이, HTML 레이아웃을 구성해주실 사람을 구합니다.

1. title : HY-CoRA
2. 한마디 작성을 위한 html 코드 작성 (input, ul 태그)

본인 역량에 따라 CSS를 입히셔도 괜찮습니다! (`public/styleshetts/style.css`)

**Comment by sochubert** [comment]
지원 하겠습니다~

**Comment by sorongosdev** [comment]
아직 부족하지만 하고 싶습니다

**Comment by onnoo** [comment]
내일 오전에 슬랙 디엠 드릴게요!

**Comment by sorongosdev** [comment]
넵

**Comment by onnoo** [comment]
https://time.navyism.com/ 여기 사이트 우측에 있는 한마디 게시판을 따라서 만들 예정입니다!

![1](https://user-images.githubusercontent.com/29935117/95535467-7fd91b80-0a23-11eb-9bdf-b785417feedd.PNG)

**Comment by onnoo** [comment]
Solved from #14
